alertmanager:
  config:
    global:
      resolve_timeout: 5m
    receivers:
    - name: email-k8s-admin
      email_configs:
      - auth_identity: # Your email
        auth_password: # Your email account password
        auth_username: # Your email account username
        from: # The sending email
        send_resolved: true
        smarthost: smtp.gmail.com:587 # To change for each email provider
        to: # Your recipie,t
    route:
      group_interval: 4m
      group_wait: 20s
      receiver: email-k8s-admin
      repeat_interval: 4h
      routes: []
