apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: test-alert-rule
  namespace: monitoring
spec:
  groups:
    - name: test-alert-group
      rules:
        - alert: TestAlert
          expr: vector(1)
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Test Alert"
            description: "This is a test alert to verify email notifications."
