alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 20s
      group_interval: 4m
      repeat_interval: 4h
      receiver: 'email-k8s-admin'
      routes: []
    receivers:
    - name: 'email-k8s-admin'
      email_configs:
      - to: 'esteban.vincent@efrei.net'
        from: 'estebanvincent.mail@gmail.com'
        smarthost: 'smtp.gmail.com:587'
        auth_username: 'estebanvincent.mail@gmail.com'
        auth_password: 'eicsvscqwdexpdpq'
        auth_identity: 'estebanvincent.mail@gmail.com'
        send_resolved: true