apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2-devops-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2-devops-project
  template:
    metadata:
      labels:
        app: m2-devops-project
    spec:
      containers:
        - name: m2-devops-project
          image: serquand/project-devops:latest
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: m2-devops-project-service
spec:
  type: NodePort
  selector:
    app: m2-devops-project
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081